const {connect,root}=require('./browser.cjs');const fs=require('fs');
(async()=>{const c=await connect();const results=[];function assert(ok,label,detail){results.push({label,pass:!!ok,...(detail?{detail}:{})});if(!ok)console.log('FAIL',label,detail||'');}
const viewports=[[1672,941],[1536,864],[1440,900],[1366,768],[1280,800],[1024,768],[768,1024],[390,844]];
const pages=fs.readdirSync(root).filter(x=>x.endsWith('.html'));
await c.send('Page.enable');
for(const [w,h] of viewports){await c.load('index.html',w,h);const d=await c.evaluate(`(()=>{const cards=[...document.querySelectorAll('.kpi')];return {overflow:document.documentElement.scrollWidth>innerWidth,heights:cards.map(x=>x.offsetHeight),tops:cards.map(x=>x.offsetTop),clip:cards.some(x=>x.scrollWidth>x.clientWidth),scale:visualViewport.scale}})()`);assert(!d.overflow&& !d.clip&&d.scale===1,`Dashboard ${w}×${h}`,d);if(w>=1280)assert(new Set(d.tops).size===1&&new Set(d.heights).size===1,`Six equal KPI cards ${w}`);if(w===1366||w===1672||w===390){const s=await c.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(root+`verification/dashboard-${w}.png`,Buffer.from(s.data,'base64'));}}
for(const file of pages){for(const w of [1366,1024,768,390]){await c.load(file,w,w===390?844:768);const d=await c.evaluate(`(()=>{document.querySelectorAll('img').forEach(x=>x.loading='eager');return {overflow:document.documentElement.scrollWidth>innerWidth,broken:[...document.images].filter(x=>x.complete&&!x.naturalWidth).map(x=>x.getAttribute('src')),active:document.querySelectorAll('.nav-link.active').length,rows:document.querySelectorAll('[data-table-module] tbody tr').length}})()`);assert(!d.overflow&&!d.broken.length&&d.active===1,`${file} ${w}px`,d);}}
await c.load('products.html');
const evals=async(expr)=>c.evaluate(`(()=>{${expr}})()`);
const search=async value=>evals(`const s=document.querySelector('[data-search]');s.value=${JSON.stringify(value)};s.dispatchEvent(new Event('input'));return [...document.querySelectorAll('tbody tr')].filter(x=>!x.hidden).length;`);
const filter=async(key,value)=>evals(`const s=document.querySelector('[data-filter="${key}"]');s.value=${JSON.stringify(value)};s.dispatchEvent(new Event('change'));return [...document.querySelectorAll('tbody tr')].filter(x=>!x.hidden).map(x=>({...x.dataset}));`);
const visible=()=>c.evaluate(`[...document.querySelectorAll('tbody tr')].filter(x=>!x.hidden).length`);
assert(await visible()===10,'Default 10 rows');
await search('valve');await filter('category','Industrial Valves');await filter('brand','Kitz');let data=await filter('status','Active');assert(data.length>0&&data.every(x=>x.category==='Industrial Valves'&&x.brand==='Kitz'&&x.status==='Active'&&x.name.toLowerCase().includes('valve')),'Combined product filters',data.length);
assert(await c.evaluate(`document.querySelectorAll('.filter-chips button').length`)===5,'Filter chips and Clear All');
await search('impossible-zzzz');assert(await visible()===0&&await c.evaluate(`!document.querySelector('.empty-state').hidden`),'No-result state');
await c.evaluate(`document.querySelector('[data-reset]').click()`);assert(await visible()===10,'Reset filters');
await c.evaluate(`document.querySelector('[data-next]').click()`);assert((await c.evaluate(`document.querySelector('[data-result-count]').textContent`)).includes('11–20 of 60'),'Pagination next');
await evals(`const s=document.querySelector('[data-page-size]');s.value='25';s.dispatchEvent(new Event('change'));`);assert(await visible()===25,'25 rows per page');
await evals(`const s=document.querySelector('[data-page-size]');s.value='50';s.dispatchEvent(new Event('change'));`);assert(await visible()===50,'50 rows per page');
await c.evaluate(`document.querySelector('[data-sort="1"]').click()`);let names=await c.evaluate(`[...document.querySelectorAll('tbody tr')].map(x=>x.cells[1].textContent.trim())`);assert(names.every((x,i)=>i===0||names[i-1].localeCompare(x,undefined,{numeric:true,sensitivity:'base'})<=0),'Ascending sorting');
await c.evaluate(`document.querySelector('[data-select-all]').click()`);assert((await c.evaluate(`document.querySelector('[data-selected]').textContent`))==='50 selected','Bulk selection');
await c.evaluate(`document.querySelector('[data-select-all]').click()`);assert((await c.evaluate(`document.querySelector('[data-selected]').textContent`))==='0 selected','Bulk deselection');
await c.load('inquiries.html');data=await filter('status','New');assert(data.length===8&&data.every(x=>x.status==='New'),'Inquiry status filter');await c.evaluate(`document.querySelector('[data-reset]').click();document.querySelector('[data-next]').click()`);assert((await c.evaluate(`document.querySelector('[data-result-count]').textContent`)).includes('11–20 of 48'),'Inquiry pagination');
await c.load('product-create.html');await evals(`const s=document.getElementById('category');s.value='Pumps';s.dispatchEvent(new Event('change'));`);const opts=await c.evaluate(`[...document.getElementById('subcategory').options].filter(x=>!x.disabled&&x.value).map(x=>x.value)`);assert(opts.length===2&&opts.includes('Centrifugal Pumps'),'Dependent taxonomy selects',opts);
await c.load('index.html',390,844);await c.evaluate(`document.querySelector('.topbar [data-sidebar]').click()`);assert(await c.evaluate(`document.querySelector('.sidebar').getBoundingClientRect().left===0||document.body.classList.contains('sidebar-open')`),'Mobile sidebar opens');
await c.load('index.html');const large=await evals(`document.querySelectorAll('.kpi-value').forEach(x=>x.textContent='128,450');return [...document.querySelectorAll('.kpi')].every(x=>x.scrollWidth<=x.clientWidth);`);assert(large,'Future KPI values contained');
await c.send('Emulation.setScriptExecutionDisabled',{value:true});
for(const file of pages){await c.load(file,1366,768);const d=await c.evaluate(`({body:document.querySelector('main').innerText.length,rows:document.querySelectorAll('[data-table-module] tbody tr').length,visible:[...document.querySelectorAll('[data-table-module] tbody tr')].filter(x=>!x.hidden).length,forms:document.querySelectorAll('form').length})`);assert(d.body>100&&d.rows===d.visible,`No JavaScript: ${file}`,d);}
await c.send('Emulation.setScriptExecutionDisabled',{value:false});
await c.load('products.html',1366,768);const ss=await c.send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(root+'verification/products-1366.png',Buffer.from(ss.data,'base64'));
fs.writeFileSync(root+'verification/results.json',JSON.stringify({date:'2026-10-09',browser:'Chrome headless',zoom:'100%; deviceScaleFactor=1',checks:results.length,passed:results.filter(x=>x.pass).length,results},null,2));console.log(JSON.stringify({checks:results.length,passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass)},null,2));c.ws.close();})();
